AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A stack that manages running the WSB Stock Ticker Bot
Parameters:
  Version:
    Type: String
    Description: The runtime version of the WSB Ticker Bot
Resources:
  WsbTickerBot:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: WsbTickerBot
      Handler: lambda_function_bot.run_bot
      Runtime: python3.8
      CodeUri: ../src/.
      Description: Run the WSB Ticker Bot
      Environment:
        Variables:
          BotUserName: WSBStockTickerBot
          NotificationsQueueUrl: !Ref NotificationsQueue
      Timeout: 899
      MemorySize: 256
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AmazonDynamoDBFullAccess
        - AmazonSQSFullAccess
      Layers:
        - !Ref libs
      Events:
        ScheduledRun:
          Type: Schedule
          Properties:
            Schedule: 'cron(0/10 * * * ? *)'
            Name: RunEveryTenMinutes
            Input: !Sub "{\"version\": \"${Version}\"}"
            Description: Run every 10 minutes
      Tags:
        Version: !Ref Version

  WsbTickerBotNotifier0:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: WsbTickerBotNotifier0
      Handler: lambda_function_notifier.process_notifications
      Runtime: python3.8
      CodeUri: ../src/.
      Description: Run the WSB Ticker Bot
      Environment:
        Variables:
          BotUserName: WSBStockTickerBot
          NotificationsQueueUrl: !Ref NotificationsQueue
      Timeout: 899
      MemorySize: 256
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AmazonDynamoDBFullAccess
        - AmazonSQSFullAccess
      Layers:
        - !Ref libs
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt NotificationsQueue.Arn
            BatchSize: 10
      Tags:
        Version: !Ref Version

  WsbTickerBotNotifier1:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: WsbTickerBotNotifier1
      Handler: lambda_function_notifier.process_notifications
      Runtime: python3.8
      CodeUri: ../src/.
      Description: Run the WSB Ticker Bot
      Environment:
        Variables:
          BotUserName: WSBTickerBotHandler
          NotificationsQueueUrl: !Ref NotificationsQueue
      Timeout: 899
      MemorySize: 256
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AmazonDynamoDBFullAccess
        - AmazonSQSFullAccess
      Layers:
        - !Ref libs
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt NotificationsQueue.Arn
            BatchSize: 10
      Tags:
        Version: !Ref Version

  NotificationsQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 900

  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: wsb-ticker-bot-lib
      Description: Dependencies for the WSB Ticker Bot app
      ContentUri: package/.
      CompatibleRuntimes:
        - python3.8